import type {
  NextFunction,
  Request,
  Response
} from "express";

import { ZodError } from "zod";
import { AppError } from "../utils/errors.js";

/**
 * Mounted after all routes.
 *
 * Returns:
 * {
 *   success: false,
 *   error: {
 *     code,
 *     message
 *   }
 * }
 */
export function notFoundHandler(
  _request: Request,
  response: Response
): void {
  response.status(404).json({
    success: false,
    error: {
      code: "NOT_FOUND",
      message:
        "The requested endpoint does not exist."
    }
  });
}

/**
 * Centralized error handler.
 *
 * Must be registered after every route and
 * after the notFoundHandler.
 *
 * It never exposes stack traces or raw
 * database errors to the client.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function errorHandler(
  error: unknown,
  _request: Request,
  response: Response,
  _next: NextFunction
): void {
  /**
   * Known application errors.
   */
  if (error instanceof AppError) {
    response.status(error.statusCode).json({
      success: false,
      error: {
        code: error.code,
        message: error.message,
        ...(error.details
          ? { details: error.details }
          : {})
      }
    });

    return;
  }

  /**
   * Zod validation errors.
   */
  if (error instanceof ZodError) {
    response.status(400).json({
      success: false,
      error: {
        code: "VALIDATION_ERROR",
        message:
          "The request data is invalid.",
        details:
          error.flatten().fieldErrors
      }
    });

    return;
  }

  /**
   * Invalid JSON body errors generated by
   * express.json().
   */
  if (
    error instanceof SyntaxError &&
    "status" in error &&
    (error as { status?: number }).status === 400 &&
    "body" in error
  ) {
    response.status(400).json({
      success: false,
      error: {
        code: "VALIDATION_ERROR",
        message:
          "The request body contains invalid JSON."
      }
    });

    return;
  }

  /**
   * Unexpected errors.
   *
   * Log the original error on the backend,
   * but return only a safe message.
   */
  console.error(error);

  response.status(500).json({
    success: false,
    error: {
      code: "INTERNAL_ERROR",
      message:
        "An internal server error occurred."
    }
  });
}